layers:
  - name: base
    title: base
    sources: [my_source]

services:
  tms:
    origin: 'nw'
    srs: ['EPSG:900913']

sources:
  my_source:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://a.tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png
  my_source2:
    type: wms
    req:
       url: https://image.discomap.eea.europa.eu/arcgis/services/GioLand/HRIM_HR_TrueColour_2018/ImageServer/WMSServer
       layers: 0
       transparent: false
