services:
  tms:
    origin: sw
        
layers:
  - name: base
    title: Base Layer
    sources: [my_cache]

caches:
  my_cache:
    grids: [my_grid]
    sources: [my_cache_in]
  my_cache_in:
    grids: [my_grid]
    sources: [my_source]

sources:
  my_source:
     type: tile
     url: http://tile.stamen.com/terrain/%(z)s/%(x)s/%(y)s.jpg
     grid: my_grid

grids:
  my_grid:
    srs: EPSG:3857
    origin: sw